DROP TABLE IF EXISTS OrgActivities;
DROP TABLE IF EXISTS OrgVariants;
DROP TABLE IF EXISTS Orgs;
DROP TABLE IF EXISTS OrgTypes;
DROP TABLE IF EXISTS Sources;
DROP TABLE IF EXISTS Roles;
DROP TABLE IF EXISTS Countries;
DROP TABLE IF EXISTS Sectors;
DROP TABLE IF EXISTS SectorVocabularies;
DROP TABLE IF EXISTS Activities;

CREATE TABLE Activities (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  code VARCHAR(512) UNIQUE NOT NULL,
  name VARCHAR(2048) NOT NULL,
  is_humanitarian BOOL DEFAULT FALSE
);

CREATE TABLE SectorVocabularies (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  code VARCHAR(32) UNIQUE NOT NULL,
  name VARCHAR(512) NOT NULL
);

CREATE TABLE Sectors (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  code VARCHAR(256) UNIQUE NOT NULL,
  vocabulary_ref INT NOT NULL,
  name VARCHAR(512) NOT NULL,
  FOREIGN KEY (vocabulary_ref) REFERENCES SectorVocabularies(id)
);

CREATE TABLE Countries (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  code CHAR(2) UNIQUE NOT NULL,
  name VARCHAR(256) NOT NULL
);

CREATE TABLE Roles (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  code VARCHAR(16) UNIQUE NOT NULL,
  name VARCHAR(128) NOT NULL
);

CREATE TABLE Sources (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  code VARCHAR(16) UNIQUE NOT NULL,
  name VARCHAR(128) NOT NULL
);

CREATE TABLE OrgTypes (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  code VARCHAR(8) UNIQUE NOT NULL,
  name VARCHAR(32) NOT NULL
);

CREATE TABLE Orgs (
  id int PRIMARY KEY NOT NULL AUTO_INCREMENT,
  code VARCHAR(512) UNIQUE NOT NULL,
  type INT NOT NULL,
  name VARCHAR(1024) NOT NULL,
  FOREIGN KEY (type) REFERENCES OrgTypes(id)
);

CREATE TABLE OrgVariants (
  id int PRIMARY KEY NOT NULL AUTO_INCREMENT,
  code VARCHAR(512) UNIQUE NOT NULL,
  type INT NOT NULL,
  name VARCHAR(1024) NOT NULL,
  org_ref INT,
  FOREIGN KEY (type) REFERENCES OrgTypes(id),
  FOREIGN KEY (org_ref) REFERENCES Orgs(id)
);

CREATE TABLE OrgActivities (
  activity_ref INT NOT NULL,
  org_variant_ref INT NOT NULL,
  sector_ref INT NOT NULL,
  country_ref INT NOT NULL,
  role_ref INT NOT NULL,
  source_ref INT NOT NULL,
  relationship_index INT,
  UNIQUE(activity_ref, org_variant_ref, sector_ref, country_ref, role_ref, source_ref, relationship_index),
  FOREIGN KEY (activity_ref) REFERENCES Activities(id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (org_variant_ref) REFERENCES OrgVariants(id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (sector_ref) REFERENCES Sectors(id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (country_ref) REFERENCES Countries(id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (role_ref) REFERENCES Roles(id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (source_ref) REFERENCES Sources(id)
    ON DELETE CASCADE ON UPDATE CASCADE
);


